- name: Stoping containers
  shell: docker-compose stop wordpress
  args:
    chdir: /var/lib/jenkins

- name: Remove stop containers
  shell: docker rm jenkins_wordpress_1

- name: Remove old files
  shell: rm -rf /data/wordpress/wordpress/*

- name: copy backup
  shell: rsync -avH /data/backhttpd/ /data/wordpress/wordpress/

- name: Restor docker compose
  copy:
    src: docker-compose.yml
    ddst: /var/lib/jenkins/

- name: Run docker-compose up
  shell: docker-compose up -d
  args:
    chdir: /var/lib/jenkins