    - name: Create a directory wordpress
      file:
        path: /data/backhttpd
        state: directory
        owner: jenkins
        group: jenkins
        mode: 0755

    - name: Create a directory mariadb
      file:
        path: /data/backbd
        state: directory
        owner: jenkins
        group: jenkins
        mode: 0755

    - name: Make Backup files
      shell: sudo rsync -avH /data/wordpress/wordpress/ /data/backhttpd/

    - name: Make Backup BD
      shell: sudo rsync -avH /data/mariadb/mariadb/ /data/backbd/

    - name: Stoping containers
      shell: docker-compose stop wordpress
      args:
        chdir: /var/lib/jenkins

    - name: Remove stop containers
      shell: docker rm jenkins_wordpress_1

    - name: Copy compose
      template:
        src: docker-compose.yml
        dest: /var/lib/jenkins/
        owner: jenkins
        group: jenkins
        mode: 0644 

    - name: Run docker-compose up
      shell: docker-compose up -d
      args:
        chdir: /var/lib/jenkins    

