    - name: Create a directory wordpress
      file:
        path: /data/backhttpd
        state: directory
        owner: jenkins
        group: jenkins
        mode: 0755

    - name: Create a directory mariadb
      file:
        path: /data/backbd
        state: directory
        owner: jenkins
        group: jenkins
        mode: 0755

    - name: Make Backup files
      shell: sudo rsync -avH /data/wordpress/wordpress/ /data/backhttpd/

    - name: Make Backup BD
      shell: sudo rsync -avH /data/mariadb/mariadb/ /data/backbd/

    - name: Stoping containers
      shell: docker-compose -f docker-compose-main.yml stop wordpress
      args:
        chdir: /var/lib/jenkins

    - name: Remove stop containers
      shell: docker rm jenkins_wordpress_1

    - name: Copy compose
      template:
        src: docker-compose.yml
        dest: /var/lib/jenkins/
        owner: jenkins
        group: jenkins
        mode: 0644 

    - name: Run docker-compose up
      shell: docker-compose up -d
      args:
        chdir: /var/lib/jenkins 

    - name: Pause for runing app
      pause:
        seconds: 60       

    - name: Check Status
      block:
        - name: Check content to the site
          uri:
            url: "http://192.168.100.11:8080"
            return_content: yes
          register: out
          failed_when: "'heklkklj' not in out.content"
        - name: Print out
          debug:
            msg: "{{ out }}"
      rescue:
        - name: Notify in Slack 
          slack:
            username: 'Ansible sender'
            color: danger
            icon_url: https://logos-download.com/wp-content/uploads/2016/10/Ansible_logo.png
            token: "TFBPBNB2L/B01FCBWEN5B/HMopSvqM5zsMX6Csum7egYty"
            channel: "#deploy_project"
            msg: "Update is failed"

        - name: Rollback to previous version app
          include_role:
            name: rollback